name: slow_control_table
broker: rabbit_broker
keys: 'sensor_value.#'
module: SensorLogger
sensor_type_map_table: id_map
data_tables_dict:
  numeric: numeric_table
  string: string_table
  json: json_table
database_server: psql_db
database_name: cage_sc_db
endpoints:
  - name: id_map
    module: SQLTable
    schema: public
    table_name: endpoint_id_map
  - name: numeric_table
    module: SQLTable
    schema: public
    table_name: numeric_data
    required_insert_names:
      - endpoint_name
      - timestamp
      - value_raw
    optional_insert_names:
      - value_cal
      - memo
  - name: string_table
    module: SQLTable
    schema: public
    table_name: string_data
    required_insert_names:
      - endpoint_name
      - timestamp
      - value_raw
    optional_insert_names:
      - value_cal
      - memo
  - name: json_table
    module: SQLTable
    schema: public
    table_name: json_data
    required_insert_names:
      - endpoint_name
      - timestamp
      - value_raw
    optional_insert_names:
      - value_cal
      - memo
