version: '2'

services:
    # a rabbit broker
    rabbit_broker:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
    # a psql database
    psql_db:
        build: postgresql
        volumes:
          - db:/var/lib/postgresql/data
        ports:
          - 5432:5432
    metabase:
        image: metabase/metabase:v0.31.2
        volumes:
          - mb:/metabase-data
        ports:
          - 3000:3000
        environment:
          - MB_DB_FILE=/metabase-data/metabase.db
    # dragonfly service
    cesi:
        build: cesi
        ports:
          - 5000:5000
        restart: on-failure
    dragonfly:
        build: dragonfly
        command: supervisord
        depends_on:
          - rabbit_broker
          - psql_db
        ## These volumes can be added for easier development
        ## to use them, you must connect and execute `python setup.py develop`
        ## in each to build the requisite python objects (one time only)
        volumes:
            - ./cage_config.json:/root/.cage_config.json
            # the following mount is the dragonfly config files
            - ./dragonfly/config:/config
          #  - ./dragonfly/dripline:/code/dripline
          #  - ./dragonfly/dragonfly:/code/dragonfly
        ports:
          - 9001:9001
        restart: on-failure

volumes:
    db:
    mb:
